select * from chat_logs;

CREATE TABLE chat_logs (
    chat_id SERIAL PRIMARY KEY,
    user_id INT NULL REFERENCES users(user_id) ON DELETE SET NULL,
    session_id VARCHAR(100),               -- mã phiên trò chuyện (nếu có)
    sender VARCHAR(20) NOT NULL,           -- 'user' hoặc 'bot'
    message TEXT NOT NULL,                 -- nội dung câu hỏi / trả lời
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
TRUNCATE TABLE chat_logs RESTART IDENTITY CASCADE;

INSERT INTO plants (common_name, origin, species_id, description, is_active) VALUES
('Lúa nước', 'Châu Á', 1, 'Cây lương thực chính của người Việt Nam, được trồng chủ yếu ở đồng bằng sông Cửu Long và đồng bằng Bắc Bộ. Lúa là nguồn cung cấp carbohydrate chính, có thể trồng 2-3 vụ/năm tùy vùng. Hạt lúa sau khi xay xát thành gạo là thực phẩm thiết yếu hàng ngày.', TRUE),
('Ngô', 'Trung và Nam Mỹ', 2, 'Cây lương thực quan trọng thứ ba thế giới sau lúa mì và lúa nước. Ngô có khả năng thích ứng cao với nhiều loại đất và khí hậu. Được sử dụng làm thực phẩm, thức ăn chăn nuôi và nguyên liệu công nghiệp. Ngô giàu tinh bột, protein và các vitamin nhóm B.', TRUE),
('Xoài', 'Nam Á', 3, 'Cây ăn quả nhiệt đới được mệnh danh là "vua của các loại trái cây". Xoài có hương vị thơm ngon, giàu vitamin A, C và chất xơ. Việt Nam có nhiều giống xoài đặc sản như xoài Cát Chu, xoài Tượng, xoài Keo. Là sản phẩm xuất khẩu quan trọng.', TRUE),
('Cam', 'Trung Quốc', 4, 'Cây ăn quả họ cam chanh, nguồn cung cấp vitamin C dồi dào. Cam có tính mát, giúp giải khát và tăng cường sức đề kháng. Vỏ cam có thể sử dụng làm thuốc và gia vị. Cam Canh, cam Sành là những giống nổi tiếng ở Việt Nam.', TRUE),
('Cà phê', 'Ethiopia', 5, 'Cây công nghiệp chiến lược, Việt Nam là nước xuất khẩu cà phê lớn thứ hai thế giới. Cà phê Arabica cho chất lượng cao, hương vị tinh tế. Được trồng chủ yếu ở Tây Nguyên với khí hậu và đất đỏ bazan thích hợp. Tạo việc làm cho hàng triệu lao động.', TRUE),
('Ca cao', 'Châu Mỹ', 6, 'Cây nguyên liệu sản xuất chocolate và các sản phẩm thực phẩm. Hạt ca cao giàu chất chống oxi hóa, có lợi cho sức khỏe tim mạch. Việt Nam trồng ca cao chủ yếu ở Đông Nam Bộ và một số tỉnh Tây Nguyên. Cây có giá trị kinh tế cao.', TRUE),
('Mía', 'New Guinea', 7, 'Cây công nghiệp sản xuất đường chủ yếu, chiếm 80% sản lượng đường thế giới. Mía cũng được sử dụng để sản xuất ethanol sinh học. Việt Nam trồng mía tập trung ở miền Tây Nam Bộ. Thân mía chứa 12-18% saccharose, có thể ép lấy nước uống trực tiếp.', TRUE),
('Cà chua', 'Nam Mỹ', 8, 'Cây rau quả được trồng phổ biến, nguồn cung cấp lycopene - chất chống ung thư mạnh. Cà chua có thể ăn sống, nấu chín hoặc chế biến thành sốt, ketchup. Giàu vitamin C, K và folate. Có nhiều giống từ cherry nhỏ đến beef lớn.', TRUE),
('Ớt', 'Châu Mỹ', 9, 'Cây gia vị không thể thiếu trong ẩm thực Việt Nam. Chứa capsaicin tạo vị cay, có tác dụng kháng viêm và giảm đau. Ớt giàu vitamin C, cao hơn cam chanh. Có nhiều loại từ ớt hiểm, ớt sừng bò đến ớt chuông ngọt.', TRUE),
('Hành tây', 'Châu Á', 10, 'Cây gia vị cơ bản, được sử dụng trong hầu hết các món ăn. Hành tây chứa quercetin - chất chống oxi hóa mạnh, có tác dụng chống viêm và bảo vệ tim mạch. Có thể ăn sống, xào, hay dùng làm gia vị cho nhiều món ăn khác nhau.', TRUE),
('Cải bắp', 'Địa Trung Hải', 11, 'Cây rau lá giàu vitamin C, K và chất xơ. Cải bắp có thể ăn sống làm salad hoặc nấu chín. Chứa sulforaphane có tác dụng chống ung thư. Dễ trồng, thích ứng với khí hậu mát mẻ. Là thành phần quan trọng trong nhiều món ăn truyền thống.', TRUE),
('Xà lách', 'Địa Trung Hải', 12, 'Cây rau lá chính cho salad, ít calo nhưng giàu folate và vitamin K. Có nhiều loại như xà lách xoăn, xà lách bơ, xà lách cos. Dễ tiêu hóa, thích hợp cho người ăn kiêng. Cần khí hậu mát để phát triển tốt.', TRUE),
('Dưa chuột', 'Ấn Độ', 13, 'Cây rau quả có tính mát, chứa 95% nước, rất tốt để giải khát và thanh nhiệt. Giàu silica có lợi cho da và tóc. Có thể ăn sống, làm dưa muối hoặc nấu canh. Dễ trồng, sinh trưởng nhanh, cho năng suất cao.', TRUE),
('Bí ngô', 'Bắc Mỹ', 14, 'Cây rau củ quả giàu beta-carotene, vitamin A và chất xơ. Bí ngô có vị ngọt tự nhiên, thích hợp làm súp, bánh hoặc món tráng miệng. Hạt bí cũng có thể rang ăn, giàu protein và kẽm. Cây mọc lan rộng, cần diện tích lớn.', TRUE),
('Đậu tây', 'Châu Mỹ', 15, 'Cây họ đậu giàu protein thực vật, chất xơ và folate. Có khả năng cố định nitơ từ không khí, cải thiện độ phì nhiêu của đất. Hạt đậu có thể nấu chín, làm salad hoặc chế biến thành nhiều món ăn khác nhau. Dễ trồng và chăm sóc.', TRUE),
('Đậu tương', 'Đông Á', 16, 'Cây công nghiệp quan trọng, nguồn protein thực vật hoàn chỉnh. Nguyên liệu sản xuất dầu ăn, tương, đậu phụ, sữa đậu nành. Chứa isoflavone có lợi cho phụ nữ mãn kinh. Việt Nam nhập khẩu nhiều đậu tương để chế biến thức ăn chăn nuôi.', TRUE),
('Lạc', 'Nam Mỹ', 17, 'Cây hạt có dầu, nguồn cung cấp protein và chất béo không bão hòa tốt cho sức khỏe. Lạc có thể ăn sống, luộc, rang hoặc chế biến thành dầu, bơ lạc. Giàu niacin, folate và vitamin E. Trồng nhiều ở miền Nam với đất cát thoát nước tốt.', TRUE),
('Dừa', 'Ấn Độ Dương', 18, 'Cây đa dụng nhất vùng nhiệt đới. Nước dừa giàu khoáng chất, cùi dừa chứa chất béo tốt. Lá dừa làm mái nhà, thân làm gỗ xây dựng. Dầu dừa có tác dụng kháng khuẩn. Cây dừa sống lâu, có thể cho sản phẩm 50-80 năm.', TRUE),
('Chuối', 'Đông Nam Á', 19, 'Cây ăn quả nhiệt đới phổ biến nhất, giàu kali, vitamin B6 và chất xơ. Chuối chín có thể ăn trực tiếp, chuối xanh nấu canh hoặc chiên. Lá chuối dùng gói bánh, hoa chuối làm rau. Cây sinh trưởng nhanh, cho quả quanh năm.', TRUE),
('Thơm', 'Nam Mỹ', 20, 'Cây ăn quả nhiệt đới có vị ngọt đặc trưng và hương thơm quyến rũ. Thơm chứa enzyme bromelain giúp tiêu hóa protein. Giàu vitamin C và manganese. Có thể ăn tươi, làm nước ép hoặc chế biến thành mứt. Phù hợp với khí hậu nhiệt đới ẩm.', TRUE),
('Đu đủ', 'Trung Mỹ', 21, 'Cây ăn quả giàu vitamin A, C và enzyme papain hỗ trợ tiêu hóa. Đu đủ xanh làm salad Thái, đu đủ chín ăn tráng miệng. Lá đu đủ có thể nấu canh hoặc làm trà. Cây sinh trưởng nhanh, ra quả sớm sau 8-12 tháng trồng.', TRUE),
('Đào', 'Trung Quốc', 22, 'Cây ăn quả ôn đới, biểu tượng của sự trường thọ trong văn hóa Á Đông. Đào giàu vitamin A, C và chất xơ. Có nhiều giống từ đào tiên ngọt đến đào chua. Cần khí hậu mát về đông để ra hoa và kết quả tốt.', TRUE),
('Táo', 'Trung Á', 23, 'Cây ăn quả ôn đới phổ biến nhất thế giới. Táo chứa pectin và quercetin tốt cho sức khỏe. Có hàng nghìn giống khác nhau về màu sắc, vị và texture. "An apple a day keeps the doctor away" - thể hiện giá trị dinh dưỡng của táo. Cần khí hậu mát về đông.', TRUE),
('Nho', 'Cận Đông', 24, 'Cây ăn quả cổ xưa, nguyên liệu chính sản xuất rượu vang. Nho chứa resveratrol - chất chống lão hóa mạnh. Có thể ăn tươi, phơi khô thành nho khô hoặc ép lấy nước. Cần khí hậu Địa Trung Hải với mùa khô và mùa mưa rõ rệt.', TRUE),
('Dâu tây', 'Bắc Mỹ và Chile', 25, 'Cây ăn quả nhỏ có hàm lượng vitamin C cao hơn cam. Dâu tây chứa anthocyanin tạo màu đỏ và chống oxi hóa. Có thể ăn tươi, làm mứt, bánh hoặc kem. Cần đất thoát nước tốt và khí hậu mát mẻ để phát triển.', TRUE),
('Mâm xôi', 'Châu Âu', 26, 'Cây ăn quả dại có hàm lượng chất xơ và vitamin C cao. Mâm xôi đỏ chứa ketone giúp đốt cháy chất béo. Có thể ăn tươi, làm mứt hoặc sấy khô. Cây mọc thành bụi, dễ nhân giống và chăm sóc.', TRUE),
('Việt quất', 'Bắc Mỹ', 27, 'Siêu thực phẩm với hàm lượng chất chống oxi hóa cao nhất. Việt quất tốt cho trí nhớ và thị lực. Có thể ăn tươi, làm mứt hoặc thêm vào bánh. Cần đất chua và khí hậu mát để phát triển tốt.', TRUE),
('Bơ', 'Trung Mỹ', 28, 'Cây ăn quả giàu chất béo không bão hòa tốt cho tim mạch. Bơ chứa folate, kali và vitamin K. Có thể ăn trực tiếp, làm sinh tố hoặc guacamole. Cây cần nhiều nước và khí hậu ôn hòa để phát triển.', TRUE),
('Sung', 'Tây Á', 29, 'Cây ăn quả cổ xưa được nhắc đến trong nhiều tôn giáo. Sung tươi ngọt và mềm, sung khô giàu chất xơ và khoáng chất. Lá sung có thể dùng làm thuốc dân gian. Cây thích ứng với nhiều loại đất và khí hậu.', TRUE),
('Lựu', 'Iran', 30, 'Cây ăn quả có nhiều hạt đỏ ruby, biểu tượng của sự thịnh vượng. Lựu giàu punicalagin - chất chống oxi hóa mạnh. Có tác dụng chống viêm và bảo vệ tim mạch. Có thể ăn tươi hoặc ép lấy nước. Cây chịu hạn tốt.', TRUE),
('Ổi', 'Trung Mỹ', 31, 'Cây ăn quả nhiệt đới có hàm lượng vitamin C gấp 4-5 lần cam. Ổi có vị ngọt dịu, thịt quả giòn. Lá ổi có thể pha trà, có tác dụng chống tiêu chảy. Cây dễ trồng, chịu hạn tốt, cho quả quanh năm.', TRUE),
('Sim', 'Ấn Độ', 32, 'Cây ăn quả nhỏ màu tím đen, chứa nhiều chất chống oxi hóa. Sim có vị chua ngọt đặc trưng, thường được làm rượu hoặc mứt. Cây mọc hoang, thích ứng với đất nghèo và khí hậu khắc nghiệt.', TRUE),
('Vải thiều', 'Trung Quốc', 33, 'Cây ăn quả nhiệt đới quý hiếm với thịt trong trắng ngọt như mật. Vải giàu vitamin C và đồng. Vải Thiều Lục Ngạn, Hải Dương là đặc sản nổi tiếng. Cây khó trồng, cần kỹ thuật cao và điều kiện thời tiết phù hợp.', TRUE),
('Nhãn', 'Đông Nam Á', 34, 'Cây ăn quả nhiệt đới có thịt trong trắng, vị ngọt dịu. Nhãn giàu vitamin C, iron và potassium. Hạt nhãn có thể rang ăn hoặc pha trà. Nhãn lồng Hưng Yên là giống đặc sản. Cây cần khí hậu ẩm và đất thoát nước tốt.', TRUE),
('Chôm chôm', 'Đông Nam Á', 35, 'Cây ăn quả nhiệt đới có vỏ màu đỏ đầy gai. Thịt trong trắng ngọt, giòn như vải. Chôm chôm giàu vitamin C và iron. Là đặc sản của miền Nam Việt Nam. Cây cần nhiệt độ cao và độ ẩm lớn để phát triển.', TRUE),
('Sầu riêng', 'Đông Nam Á', 36, 'Vua của các loại trái cây với hương vị đậm đà, độc đáo. Sầu riêng giàu calories, vitamin B và potassium. Có hàng trăm giống khác nhau. Ri6 là giống nổi tiếng của Việt Nam. Cây cần khí hậu nhiệt đới ẩm và đất phì nhiêu.', TRUE),
('Mít', 'Ấn Độ', 37, 'Cây cho quả lớn nhất thế giới, có thể nặng đến 50kg. Mít non có thể nấu canh, mít chín ăn tráng miệng. Hạt mít luộc ăn như khoai. Lá mít dùng làm thức ăn gia súc. Cây thích ứng tốt với khí hậu nhiệt đới.', TRUE),
('Măng cụt', 'Đông Nam Á', 38, 'Nữ hoàng của các loại trái cây với vỏ tím đen, thịt trong trắng ngọt thanh. Măng cụt chứa xanthone - chất chống viêm mạnh. Cây rất khó trồng, cần 7-10 năm mới ra quả. Là loại quả đắt tiền và quý hiếm.', TRUE),
('Bòn bon', 'Đông Nam Á', 39, 'Cây ăn quả địa phương với thịt trong trắng, vị ngọt chua. Có thể ăn tươi hoặc làm mứt. Vỏ và hạt có thể sử dụng trong y học cổ truyền. Cây thích ứng tốt với khí hậu nhiệt đới ẩm của Việt Nam.', TRUE),
('Bưởi', 'Đông Nam Á', 40, 'Cây ăn quả lớn nhất họ cam chanh với thịt trong có thể màu trắng, hồng hoặc đỏ. Bưởi giàu vitamin C và lycopene. Bưởi Da Xanh, Năm Roi là các giống nổi tiếng. Vỏ bưởi có thể làm mứt hoặc tinh dầu.', TRUE),
('Quýt', 'Đông Nam Á', 41, 'Cây ăn quả nhỏ họ cam chanh, dễ bóc vỏ và ăn. Quýt giàu vitamin C và flavonoid. Vỏ quýt khô dùng làm thuốc trong Đông y. Cây thích ứng tốt với khí hậu cận nhiệt đới, dễ trồng và chăm sóc.', TRUE),
('Chanh', 'Đông Nam Á', 42, 'Cây gia vị và ăn quả không thể thiếu trong ẩm thực Việt Nam. Chanh giàu vitamin C và acid citric. Sử dụng làm nước chấm, gia vị hoặc đồ uống. Lá chanh có hương thơm đặc trưng, dùng nấu cà ri.', TRUE),
('Khế', 'Đông Nam Á', 43, 'Cây ăn quả có hình dạng ngôi sao độc đáo khi cắt ngang. Khế chua giàu vitamin C, khế ngọt có thể ăn tráng miệng. Khế có tác dụng hạ huyết áp và cholesterol. Cây dễ trồng, ra quả quanh năm.', TRUE),
('Na', 'Châu Mỹ', 44, 'Cây ăn quả nhiệt đới với thịt trong trắng ngọt như kem. Na giàu vitamin C, kali và chất xơ. Hạt na độc, không ăn được. Cây thích ứng tốt với khí hậu khô, chịu hạn tốt. Na Thái Lan là giống được ưa chuộng.', TRUE),
('Mãng cầu xiêm', 'Châu Mỹ', 45, 'Cây ăn quả nhiệt đới có quả lớn, vỏ xanh gai mềm. Thịt trong trắng ngọt, có hương vị đặc biệt kết hợp giữa chua và ngọt. Mãng cầu xiêm giàu vitamin C, chất xơ và carbohydrate. Có tác dụng tăng cường miễn dịch và hỗ trợ tiêu hóa. Cây sinh trưởng mạnh trong khí hậu nhiệt đới ẩm.', TRUE),
('Cóc', 'Melanesia', 46, 'Cây ăn quả nhiệt đới có vị chua ngọt đặc trưng, thường được gọi là táo tây nhiệt đới. Cóc giàu vitamin C, chất xơ và enzyme. Quả non có thể làm salad, quả chín ăn tráng miệng. Lá cóc có thể sử dụng làm thuốc dân gian để điều trị tiêu chảy. Cây thích ứng tốt với nhiều loại đất.', TRUE),
('Vú sữa', 'Trung Mỹ', 47, 'Cây ăn quả nhiệt đới có thịt trong mịn màng như kem, vị ngọt đậm đà. Vú sữa giàu vitamin C, calcium và phosphorus. Quả có thể ăn tươi hoặc làm sinh tố. Cây cần khí hậu ẩm và đất thoát nước tốt. Là loại cây ăn quả còn ít phổ biến ở Việt Nam.', TRUE),
('Hồng', 'Trung Quốc', 48, 'Cây ăn quả ôn đới với quả có màu cam đỏ đặc trưng. Hồng giàu beta-carotene, vitamin A và tannin. Có hai loại chính: hồng sắt (ăn cứng) và hồng mềm (để chín mềm mới ăn). Lá hồng có thể pha trà, có tác dụng hạ huyết áp. Cây cần thời gian lạnh để ra hoa kết quả.', TRUE),
('Kiwi', 'Trung Quốc', 49, 'Cây ăn quả ôn đới có hàm lượng vitamin C cao nhất trong các loại trái cây. Kiwi chứa enzyme actinidin giúp tiêu hóa protein. Có thể ăn tươi, làm sinh tố hoặc salad. Vỏ kiwi cũng ăn được và chứa nhiều chất xơ. Cây cần khí hậu ôn đới mát và độ ẩm cao.', TRUE),
('Chà là', 'Bắc Phi', 50, 'Cây ăn quả sa mạc có khả năng chịu hạn cực tốt. Chà là giàu glucose, fructose và chất xơ. Được mệnh danh là "bánh mì của sa mạc" vì giá trị dinh dưỡng cao. Có thể ăn tươi hoặc sấy khô bảo quản lâu. Cây cọ này có thể sống trong điều kiện khắc nghiệt của sa mạc.', TRUE);
